### ISSUE TITLE
Closing tab in wrong window

### ISSUE THREAD

**Issue by JonathanGale** [zimocode/smartup#1]
Hi there,
Love this little program!
When having Chrome open in 2 windows, the Close Tab references the tab that is focused, not the tab that is underneath the mouse pointer. If I'm running chrome windows across 2 monitors, I'll often hover over a different window and close the wrong tab.

Running Mac - High Sierra, if it's relevant. Haven't tested if the bug is cross-platform or cross-browser.

**Comment by zimocode** [comment]
I don't have a mac device. All are not tested on this platform. However, as far as I understand it, if after a non-current window operation gesture, the window should become focused window?
