### ISSUE TITLE
在新标签页不能使用

### ISSUE THREAD

**Issue by Kilitao7** [zimocode/smartup#104]
在新版edge浏览器中，不管是自带的新标签页还是infinity标签页都显示不能正常运行。
这个问题可以解决吗

**Comment by zimocode** [comment]
浏览器本身限制了扩展在这类页面运行，所有，无解。

**Comment by qq57240** [comment]
> 浏览器本身限制了扩展在这类页面运行，所有，无解。
这就是为啥总是不能下决心放弃360极速的原因，插件和浏览器原生功能比，存在的限制比较让人头大。
