### ISSUE TITLE
What's the difference between a SimpleDrag and a SuperDrag? Can you add an explanation to eg the extension page?

### ISSUE THREAD

**Issue by ars4l4n** [zimocode/smartup#107]
I couldn't find one on google, didn't see a difference between the settings of the two or in functionality.

**Comment by zimocode** [comment]
SuperDrag like mouse gestures, you may add more and more actions.
SimpleDrag just 8 actions, with 8 directions.

**Comment by bubblefoil** [comment]
Hi @zimocode, I really appreciate your work on this awesome extension. Anyway, it really needs a user guide! Or at least some feature description on the options page. It's not intuitive at all. I still have no idea how to activate simple/super drag gestures.

**Comment by Spok1** [comment]
@bubblefoil, сheck everything by experience and you will be happy!!!☺

**Comment by Spok1** [comment]
@bubblefoil, check everything by experience and you will be happy!!!☺

**Comment by Spok1** [comment]
@bubblefoil, check everything by experimenting and you'll be happy!!!!!!☺
