### ISSUE TITLE
Strange requests to external websites in the source code

### ISSUE THREAD

**Issue by ghost** [zimocode/smartup#110]
Hi. I found in the source code of this extension some strange requests to the external websites. Here you can see them: 

![Strange code](https://i.imgur.com/qXe7hVs.png)

And here you can see example of the external content: 

![Strange external content](https://i.imgur.com/Rin0i3h.png) 

I don't know when exactly this requests are sent, or whether they are sent at all, but this extension definitely doesn't need for it's work the data that you can see on the second screenshot. **So what are all of this?**

**Comment by sam2085-19** [comment]
+1 So what are all of this? Can the developer at the very least clarify?

**Comment by davidhdez** [comment]
It's the Mini APP's list menu, you can check it with DOWN RIGHT UP gesture

**Comment by sam2085-19** [comment]
> It's the Mini APP's list menu, you can check it with DOWN RIGHT UP gesture

Cool thanks for the answer 'mini app list' but such a weird thing to add to an mouse gesture addon.

**Comment by ryanbuening** [comment]
Might be related to the advertisements...

![image](https://user-images.githubusercontent.com/812974/106794615-18288b00-6627-11eb-94d6-b8cc4d93aed8.png)

**Comment by zimocode** [comment]
1) like @ryanbuening said, it get info to show ads.
2) get online info for some mini-apps or actions.

**Comment by random-un** [comment]
@zimocode -- can you share details on the data collection / ad serving that this extension includes? I'm doing my best to use extensions that have limited privacy concerns. 

I see your short, newly released privacy statement is [here](https://privacy.zimoapps.com/smartup/) -- wondering how the details in this bug align with the notes on the privacy statemtn

![image](https://user-images.githubusercontent.com/35006176/135148597-5cd28ce4-d598-4cdb-b253-9d4315871ef2.png)


Thanks so much for your guidance here. Have been using your extension for many years and have really enjoyed it. Would prefer not to look for a new one.
