### ISSUE TITLE
Duplicate tab in background

### ISSUE THREAD

**Issue by OmTatSat** [zimocode/smartup#113]
Hello, please add the ability to duplicate tab in the background

I found an extension with this ability, but I need to do this with gesture.

That extension use the code:

chrome.commands.onCommand.addListener(function(command) {
  if (command == "duplicate-tab") {
    chrome.storage.sync.get(default_options, function(options) {
      if (options.background) {
        // Open tab in background
        chrome.tabs.query({
          currentWindow: true,
          active: true,
        }, function(tabs) {
          var tab = tabs[0];
          chrome.tabs.create({
            active: false,
            index: tab.index+1,
            openerTabId: tab.id,
            url: tab.url,
          });
        });
      }
      else {
        // Open tab in foreground
        chrome.tabs.query({
          currentWindow: true,
          active: true,
        }, function(tabs) {
          var tab = tabs[0];
          chrome.tabs.duplicate(tab.id);
        });
      }
    });
  }

May be you can adapt and use it for smartup?

**Comment by zimocode** [comment]
It will fixed in next version with an new option:
![image](https://user-images.githubusercontent.com/29518677/133922062-f0cabf38-1f31-4ea4-9cff-7993a96697c1.png)

**Comment by OmTatSat** [comment]
Great! Thank you!
