### ISSUE TITLE
Images in links

### ISSUE THREAD

**Issue by extremMiSt** [zimocode/smartup#12]
hello,

when having html like this
```
<a href="https://google.com">
   <img src ="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"/>
</a>
```
I would expect the default "open link" action to open https://google.com in a new tab
Instead it does nothing
This has been a problem on real life sites too (google images, 9gag, ...)

Brower: Firefox 62.0b14 (64-Bit)
OS: Lubuntu 18.04.1 LTS

**Comment by zimocode** [comment]
got
