### ISSUE TITLE
能否创建自定义手势使用快捷键

### ISSUE THREAD

**Issue by Abner6** [zimocode/smartup#122]
现有的添加操作不会用，能否通过画出_一个操作_之后是发送一个_快捷键_。比如画出_←↓→_代表在当前页面按下_Alt+C_

**Comment by zimocode** [comment]
能否具体点呢

**Comment by Abner6** [comment]
简单来说，创建新手势的办法增加一项。
设置步骤，画出一个图案（手势），按下一组快捷键（如Ctrl + Shift + Y）。
操作效果，当以后在任何生效页面画下该图案（手势），浏览器响应为按下了对应快捷键（如Ctrl + Shift + Y）。
例如在新版edge中，创建了某手势和“Ctrl + Shift + Y”的对应关系后，当画出该手势时，浏览器会打开集锦。
如果已有相似设置，麻烦告知怎么操作，谢谢。

**Comment by zimocode** [comment]
> 简单来说，创建新手势的办法增加一项。
> 设置步骤，画出一个图案（手势），按下一组快捷键（如Ctrl + Shift + Y）。
> 操作效果，当以后在任何生效页面画下该图案（手势），浏览器响应为按下了对应快捷键（如Ctrl + Shift + Y）。
> 例如在新版edge中，创建了某手势和“Ctrl + Shift + Y”的对应关系后，当画出该手势时，浏览器会打开集锦。
> 如果已有相似设置，麻烦告知怎么操作，谢谢。

就是使手势实现浏览器的快捷键功能？
这个似乎不能...
