### ISSUE TITLE
拖曳链接变成http://https://

### ISSUE THREAD

**Issue by dtndmd** [zimocode/smartup#123]
如题，拖曳链接打开的窗口是http://https://xxx,com

**Comment by zimocode** [comment]
能给个地址么？

**Comment by dtndmd** [comment]
> 
> 
> 能给个地址么？

抱歉没说清楚，如果拖曳包含https://链接，比如  https://github.com .打开的窗口为http://https://github.com，不过有时出现有时不出现

**Comment by zimocode** [comment]
> > 能给个地址么？
> 
> 抱歉没说清楚，如果拖曳包含[https://链接，比如](https://%E9%93%BE%E6%8E%A5%EF%BC%8C%E6%AF%94%E5%A6%82) https://github.com .打开的窗口为[http://https://github.com，不过有时出现有时不出现](http://https://github.com%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%9C%89%E6%97%B6%E5%87%BA%E7%8E%B0%E6%9C%89%E6%97%B6%E4%B8%8D%E5%87%BA%E7%8E%B0)


我想问的是，在哪个页面操作时候出现这种情况的？
另外问下，是否浏览器上安装有其它类似的扩展？

**Comment by dtndmd** [comment]
在saraba1st论坛，拖曳到链接也是同一论坛的帖子
其他拖曳扩展都禁止了，还装了Neat URL，Universal Bypass

**Comment by zimocode** [comment]
抱歉，才回复你。
刚才测试了你提到的论坛，并没有出现描述的情况，请重点检查下是否有其它的扩展的影响。暂时关闭该issue，有需要请再开。
