### ISSUE TITLE
Close Tab, select Left focuses right tab

### ISSUE THREAD

**Issue by GiftWolf** [zimocode/smartup#126]
when executing the action Close Tab, select Left, for a split second the right tab is selected before the left tab is finally selected.
I'm using Ver 6.7.141.1102 with chrome.

**Comment by zimocode** [comment]
I don't  understand what you want to express， can you give more information.

**Comment by GiftWolf** [comment]
I am referring to the "Close Tab" action where "Target Tab" is "Current" and "Selected Tab" is "Left". Lets say that I have 3 tabs open: 1,2,3. If tab 2 is active and I execute the action then tab 3 is selected for a split second. After that tab 1 is selected. Tab 2 is closed. On fast computers you might not notice that tab 3 was selected for a short amount of time but on mine it is visible.

**Comment by GiftWolf** [comment]
OK, I looked into the code. I think the problem is, that you close the current tab and then select the target tab:
```
chrome.tabs.remove(ids,function(){
	(selvalue!="s_default")?chrome.tabs.update(selid,{active:true}):null;
});
```

It has to be the other way around. First select the target tab and then remove the current tab. Otherwise chrome selects the right tab before `chrome.tabs.update()` is called.

 I hope it is understandable now. Please tell me if not.
