### ISSUE TITLE
left mouse drag (back one page) causing chrome to crash

### ISSUE THREAD

**Issue by crisjolliff** [zimocode/smartup#127]
Google Chrome Version 88.0.4324.104 (Official Build) (64-bit)
smartUp Gestures Version 6.7.141.1102
Windows 10 Home, Version 1909, OS Build 18363.1316

Intermittent fault where 'right click and drag left direction' (equivalent to Back button) causes chrome browser to crash and close completely. Reopening Chrome throws "Unexpectedly Stopped" allowing me to reopen all inadvertently closed tabs/windows.

**Comment by zimocode** [comment]
any more info？
I just test , it works.

**Comment by crisjolliff** [comment]
It's not a  consistent error, unfortunately. I wonder if it is a
compatibility issue with this and one of the other plugins/extensions I'm
using?

Here's all the extensions I'm currently using. Hope this helps.

Regards,

*Cris Jolliff*
765.562.2307

**Comment by zimocode** [comment]
The extension cant cause the browser to crash, because it does not have such high permissions.

**Comment by crisjolliff** [comment]
Guess I'll have to use something else. Thanks for looking at least.

Regards,

*Cris Jolliff*
765.562.2307
