### ISSUE TITLE
Mouse Gestures Don't Work on Trello

### ISSUE THREAD

**Issue by ryanbuening** [zimocode/smartup#128]
**Reproduction Steps**

1. Navigate to https://trello.com/b/rq2mYJNn/public-trello-boards
2. Right click and try to perform a mouse gesture.

**Expected Result**

- Gesture appears.

**Actual Result**

- Gesture does not appear.
- No errors are logged in the console.

**Comment by zimocode** [comment]
Doesn’t work perfectly in  iframe，Can't get a good solution for now.

**Comment by xiao-ju-zi** [comment]
Do you have some ideas to resolve this?

**Comment by ryanbuening** [comment]
FYI - there is somewhat of a workaround for Trello. You need to click on certain spots to be able to use mouse gestures.

![Workaround](https://user-images.githubusercontent.com/812974/118820249-186e2e80-b884-11eb-97c6-2fec93042c16.gif)
