### ISSUE TITLE
能不能支持获取更多权限提升体验

### ISSUE THREAD

**Issue by naskater** [zimocode/smartup#134]
作者能不能考虑像AutoControl Shortcut Manager那样，支持所有界面都能使用该扩展的手势功能，现在很多界面都不能使用手势，比如谷歌商店，infinity首页

**Comment by zimocode** [comment]
`AutoControl Shortcut Manager`这扩展，看名字应该是使用键盘快捷键来操作，而chrome的扩展系统对快捷键有特别的支持。而smartup的基本原理是像页面插入js，然后有js文件来完成后面的操作，但是，浏览器本身对部分页面做了限制js操作的设定，因此，无解。

**Comment by naskater** [comment]
> `AutoControl Shortcut Manager`这扩展，看名字应该是使用键盘快捷键来操作，而chrome的扩展系统对快捷键有特别的支持。而smartup的基本原理是像页面插入js，然后有js文件来完成后面的操作，但是，浏览器本身对部分页面做了限制js操作的设定，因此，无解。

原来如此，非常感谢您的解答
