### ISSUE TITLE
火狐浏览器部分鼠标手势功能缺失

### ISSUE THREAD

**Issue by QAQQIAOY** [zimocode/smartup#135]
鼠标手势火狐浏览器扩展里没有复制图像  而谷歌浏览器版本扩展里有   然后上滑和下滑更改以后就没了 改不回去了

**Comment by zimocode** [comment]
的确存在这种情况。
梳理代码后发现，对不支持复制的浏览器，则隐藏复制图像的选项。但是当前浏览器检测通过还是不显示，重置配置后却可以，相同的配置都不行，智能重置，很是奇怪。
另外，似乎复制图片的操作不起作用了吧...

**Comment by zimocode** [comment]
最新版的Firefox已经支持复制图片
