### ISSUE TITLE
Save Image As... not selecting default filename extension in 'Save as' dialogue

### ISSUE THREAD

**Issue by rawdez** [zimocode/smartup#140]
Save Image As... gesture not selecting default file type (.jpg/.png/etc.) for a file that you trying to save in 'Save as' dialogue, its All files instead.

to replicate this try to save any image on twitter or any user avatar on youtube with Save Image As... gesture.

**Comment by rawdez** [comment]
sup, zimocode, so why is it closed?

**Comment by zimocode** [comment]
I checked it ,and it will set the right file type.

**Comment by rawdez** [comment]
e.g. https://pbs.twimg.com/media/E_nVkhOXoAA8ycu?format=jpg&name=large
browser is Firefox 92, probably its a Firefox bug so probably nothing you can do unless you make your own save dialog, but still.
maybe you can submit FF bug for that issue and maybe they'd fix it, idk.

**Comment by rawdez** [comment]
and the same with that issue https://github.com/zimocode/smartup/issues/138

FF makes your addon not work properly

**Comment by zimocode** [comment]
It just error in firefox, its should a bug of firefox. I didn't find a way to fix it by now.
