### ISSUE TITLE
It does not support user-agent spoofing

### ISSUE THREAD

**Issue by emil-prager** [zimocode/smartup#155]
On Chromium based browsers, when the `--user-agent` flag is used to fake the browser (UA) or the OS, the extension stops working.
E.g. of flag value on Edge (stable) for Windows: `--user-agent="Mozilla/5.0 (X11; Linux x64; rv:91.0) Gecko/20100101 Firefox/91.0"`

PS: Very good extension, thank you! If the documentation were better and if it supported user agent spoofing, then it would have been even better, a 5 stars extension.

**Comment by zimocode** [comment]
It's browser's limitation

**Comment by emil-prager** [comment]
As a final remark: 
Taking Edge Chromium as an example, I have found out that using an extension (like User-Agent Switcher and Manager, [`extension://cnjkedgepfdpdbnepgmajmmjdjkjnifa`](https://microsoftedge.microsoft.com/addons/detail/useragent-switcher-and-m/cnjkedgepfdpdbnepgmajmmjdjkjnifa) in Microsoft Store) for user agent spoofing instead of the `--user-agent` flag, then things work normally for this gestures extension.
