### ISSUE TITLE
[feature request] disable gesutres on specified websites

### ISSUE THREAD

**Issue by dcts** [zimocode/smartup#157]
I would like to disable all gesutres only for some websites. Use case is that on some websites you need the gestures and they interfere with the smartup gestures. 

For example I play chess at chess.com, and they have functionality to write arrows on the chessboard by rightclicking and drawing on the chessboard, but unfortunately rightclick and draw left is "back" in my smar gestures settings. 

Would be great if there is a way of blacklisting websites where the gesutres will not apply.

**Comment by ryanbuening** [comment]
I came across an issue with a specific site recently as well where it would be nice to disable smartUp.

**Comment by riskoviv** [comment]
Really need this feature! For me, the extension is nearly perfect, but with this feature it'll be fully perfect!
