### ISSUE TITLE
你好，想问下，以下这些页面没有办法使用鼠标手势

### ISSUE THREAD

**Issue by zhuibo66** [zimocode/smartup#158]
1、各类包含谷歌域名的网址
2、浏览器的设置页面

挺奇怪，然后我看了下360安全浏览器，他自带的鼠标手势，是支持所有页面都可以关闭的。

**Comment by zimocode** [comment]
浏览器本身对扩展权限的限制导致的。
浏览器的内置页面，扩展商店不能使用的。
