### ISSUE TITLE
invoke the Chrome OS   screenshot functionality with a gesture?

### ISSUE THREAD

**Issue by tockschmock** [zimocode/smartup#160]
**Chrome OS** recently got nice screenshot functionalities.

A tray button invokes a dialog with three options:
- full screen screenshot (click somewhere) / or Ctrl+F5
- certain window screenshot (click into the window / no direct shortcut I am aware of
- rectangular frame screenshot (draw a frame) / or Ctrl-Shift-F5 and draw frame

Could you add these functions:
- pressing the Chrome-OS system tray screenshot button / invokes screenshot dialog
- capture the full screen
- capture a specific window
- capture a rectangular frame
to the functions avaliable to gestures?

Thanks

**Comment by zimocode** [comment]
there  is  an action - screenshot, it just `capture the full screen`
