### ISSUE TITLE
建议拖拽链接新标签打开的标签位置为相邻位置

### ISSUE THREAD

**Issue by nekojp** [zimocode/smartup#161]
从左到右，现存标签页a b c d。
在标签a拖拽打开一个链接，会在最右侧打开，变成标签页 a b c d e。
这样子关闭标签e后，会跳到d，而不是a。导致忘记自己原来是在哪个标签。
拖拽链接打开后最好是a e b c d。这样子，关闭e后会回到原来的a。
原生的右键菜单：在新标签打开链接，就是我说的这种打开策略。但是只能后台打开。
感谢～

**Comment by zimocode** [comment]
在位置选项处选择右侧即可。
![image](https://user-images.githubusercontent.com/29518677/133912932-3c8fb015-b543-4bca-9592-bb3a92bb84e0.png)
