### ISSUE TITLE
Supper Drag - Image Actions - Copy Image not working

### ISSUE THREAD

**Issue by nhan000** [zimocode/smartup#171]
As in the title, I can't copy image using the super drag. This has been an issue since I started using Smartup, probably more than a year ago, but I just learned to submit issue recently. Please have a look into it.

**Comment by nhan000** [comment]
@zimocode Sorry for pinging you but have you had time to look into this?

**Comment by zimocode** [comment]
sorry, lost this issue. 😂

**Comment by nhan000** [comment]
were you able to fix it yet? *nudge nudge* 😂

**Comment by nhan000** [comment]
Thanks a lot! I'll wait for the stable release :D
