### ISSUE TITLE
the "go to top of page" gesture does not work on various pages

### ISSUE THREAD

**Issue by tockschmock** [zimocode/smartup#175]
the "go to top of page" gesture does not work on various pages

for example not on all messages here: https://www.heise.de/newsticker/archiv/
(the page only moves some lines)

maybe you see the reason / have a fix ....

**Comment by tockschmock** [comment]
I do not understand this short notes, however the bug is not fixed for all messages in this newsticker ...
ChromeOS  Version 96.0.4664.111 (Offizieller Build) (64-Bit)

**Comment by zimocode** [comment]
> I do not understand this short notes, however the bug is not fixed for all messages in this newsticker ... ChromeOS Version 96.0.4664.111 (Offizieller Build) (64-Bit)

Just submitted to chrome web store for review, the new version has not yet started to push, Please wait for the new version to be pushed.
