### ISSUE TITLE
[Question] 自行设置滚动手势的附加滚动特效设置无效

### ISSUE THREAD

**Issue by usaginya** [zimocode/smartup#180]
### 问题实现

1. 删除默认配置的**滚动**手势
2. 重新添加**滚动**手势
3. 在页面上尝试滚动手势、结果特效无效

### 差异
* 在默认配置的**滚动**手势中、比自行设置的手势多出一个**附加滚动特效**选项、实际读取设置应该是使用此选项

#### 默认配置的**滚动**手势  和  自行配置的**滚动**手势
![默认配置的滚动手势](https://user-images.githubusercontent.com/16422300/144197469-eb9aab64-f8d8-4a30-97e2-50e62bf18f3c.jpg)
![自行添加的滚动手势](https://user-images.githubusercontent.com/16422300/144197633-c97cb247-e673-4a0c-ace5-95f6ab3bb7b7.jpg)

#### 读取默认手势的参数键和自行设置的手势参数键不一致
* 读取参数的位置
![读取参数的位置](https://user-images.githubusercontent.com/16422300/144197993-fd5a3a8b-ef62-4e9b-9985-fd1e17846285.jpg)
* 自行设置手势的实际参数
![自行设置手势的实际参数](https://user-images.githubusercontent.com/16422300/144198041-80cdf04f-afa4-4262-96c7-bbe591c9de2d.jpg)

**Comment by zimocode** [comment]
最近重写了滚动操作部分，也发现了你说的这个情况😂，新代码还没提交更新。

**Comment by usaginya** [comment]
> 最近重写了滚动操作部分，也发现了你说的这个情况😂，新代码还没提交更新。

等大佬修复了。另外还发现个需求，想用手势让链接打开在无痕模式窗口，不知道能不能实现😂

**Comment by zimocode** [comment]
> > 最近重写了滚动操作部分，也发现了你说的这个情况😂，新代码还没提交更新。
> 
> 等大佬修复了。另外还发现个需求，想用手势让链接打开在无痕模式窗口，不知道能不能实现😂

我记得是有这个功能的。

**Comment by zimocode** [comment]
在打开链接的操作里面，选择隐身窗口。
但是，我刚才测试的时候，我本地的版本似乎这个操作完全无效了😂
![image](https://user-images.githubusercontent.com/29518677/144217082-0de419e1-d343-4693-9040-eff058ecab77.png)

**Comment by usaginya** [comment]
> > > 最近重写了滚动操作部分，也发现了你说的这个情况😂，新代码还没提交更新。
> > 
> > 
> > 等大佬修复了。另外还发现个需求，想用手势让链接打开在无痕模式窗口，不知道能不能实现😂
> 
> 我记得是有这个功能的。

我想的是在当前页面上画手势，然后把当前页面直接在无痕模式下打开
