### ISSUE TITLE
能不能增加一个功能，如果关闭的是最后一个标签页，则最后的标签页直接跳转到主页，而不是退出浏览器

### ISSUE THREAD

**Issue by chwt163** [zimocode/smartup#184]
能不能增加一个功能，如果关闭的是最后一个标签页，则最后的标签页直接跳转到主页，而不是退出浏览器。
一直不喜欢 chrome 的逻辑，明明窗口标题栏有关闭按钮，为什么要把关闭最后一个标签页定义为退出浏览器呢？害得我经常关闭标签页的时候，要先看一看是不是最后一个，尤其是使用 edge 垂直标签页的时候。。。

**Comment by zimocode** [comment]
打开关闭标签页操作的页面，里面有一个选项。
![image](https://user-images.githubusercontent.com/29518677/145676700-e1e4b871-ce94-4a13-9904-5ae44f4feb3d.png)

**Comment by chwt163** [comment]
没细看，竟然没发现哈~
