### ISSUE TITLE
希望可以增加文本搜索引擎的编辑界面

### ISSUE THREAD

**Issue by gzjoeljoel** [zimocode/smartup#185]
现在“超级拖拽-文本操作-文本引擎”里面只能添加，不能删除或修改，如果添加了很多项之后就会变得非常麻烦，希望可以增加文本搜索引擎的编辑界面。

**Comment by zimocode** [comment]
这个肯定是设计有的。之前有人提过相同的问题，我记得已经修复了的呀，你这现在使用的是最新版么？

**Comment by gzjoeljoel** [comment]
版本68.1332.1118，在微软商店装的

**Comment by zimocode** [comment]
刚才电脑上查看了，搜索引擎可以进行编辑。
所有对搜索引擎的修改，在这个路径：`常规选项》搜索引擎`里面进行，不是在`超级拖曳`里面。
