### ISSUE TITLE
进入设置页面始终保持在loading阶段

### ISSUE THREAD

**Issue by Samuelsheehan** [zimocode/smartup#189]
扩展商店全新安装的扩展，但是进入设置只有loading...字样。无法进行设置，在一般页面也无法使用手势。

**Comment by zimocode** [comment]
使用的是chrome、Firefox还是edge？
在设置页，按`F12`，然后点击`console`看看是否有提示报错？

**Comment by Samuelsheehan** [comment]
**使用的是Edge浏览器**
`Error handling response: TypeError: Cannot read properties of undefined (reading 'general')
    at Object.initHandle (chrome-extension://elponhbfjjjihgeijofonnflefhcbckp/js/event.js:63:13)
    at Object.init (chrome-extension://elponhbfjjjihgeijofonnflefhcbckp/js/event.js:50:7)
    at chrome-extension://elponhbfjjjihgeijofonnflefhcbckp/js/event.js:995:7`
`Uncaught TypeError: Cannot read properties of undefined (reading 'general')
    at Object.initMenu (options.js:907:15)
    at options.js:43:8`
`DevTools 无法加载源映射： 无法加载chrome-extension://elponhbfjjjihgeijofonnflefhcbckp/js/purify.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME`
**在标题栏的设置内容也有问题，不知道扩展原因还是其他原因**
![image](https://user-images.githubusercontent.com/68676065/149781998-9e1d2a2f-86fe-43bc-a09e-3a18a600b684.png)

**Comment by zimocode** [comment]
> **使用的是Edge浏览器** `Error handling response: TypeError: Cannot read properties of undefined (reading 'general') at Object.initHandle (chrome-extension://elponhbfjjjihgeijofonnflefhcbckp/js/event.js:63:13) at Object.init (chrome-extension://elponhbfjjjihgeijofonnflefhcbckp/js/event.js:50:7) at chrome-extension://elponhbfjjjihgeijofonnflefhcbckp/js/event.js:995:7` `Uncaught TypeError: Cannot read properties of undefined (reading 'general') at Object.initMenu (options.js:907:15) at options.js:43:8` `DevTools 无法加载源映射： 无法加载chrome-extension://elponhbfjjjihgeijofonnflefhcbckp/js/purify.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME` **在标题栏的设置内容也有问题，不知道扩展原因还是其他原因** ![image](https://user-images.githubusercontent.com/68676065/149781998-9e1d2a2f-86fe-43bc-a09e-3a18a600b684.png)

请到浏览器的扩展页面查看下smartup的版本号。

**Comment by zimocode** [comment]
在设置页，按`F12`，然后点击`console`，接着输入：`JSON.stringify(config)`，然后回车。看能否显示一长串字母，如果可以的话，鼠标滚动到最后，在那一长串字母末尾有个复制按钮：`copy`，点击后复制那段文本，请提供下给我。

如果没有显示那一长串字母，请截图上传下。
Windows系统可以使用win+shift+S来快速截图，然后在这里的文本框直接ctrl+V即可完成上传。

由于是个人业余开发，缺少测试，最担心的就是出现这种完全不能使用的情况，请务必回复消息，十分感谢。😘

**Comment by Samuelsheehan** [comment]
**版本: 7.0.130.1130**
![image](https://user-images.githubusercontent.com/68676065/149798814-2413f1de-d37b-4f49-9cf7-9cc321aff16e.png)
**检查弹出窗口**
![image](https://user-images.githubusercontent.com/68676065/149799017-dc058b3b-b703-49ff-8a5a-28b7f4b3668d.png)

**Comment by zimocode** [comment]
1. 请再试一试输入：`defaultConf` ，截图看看是否有输出内容。
---
另外：
2.1 打开edge的扩展管理页面：
![image](https://user-images.githubusercontent.com/29518677/149852676-39501593-8df6-433a-bb7d-fcd59f4a59f1.png)
2.2 找到本扩展的列表，点击后面的`背景页`：
![image](https://user-images.githubusercontent.com/29518677/149852786-dc8fb3c1-e5ba-4a01-80ef-8b61b2f9b314.png)
2.3 在打开的页面中切换到`控制台`或者`console`，分别输入`config`和`defaultConf`后回车并截图。

**Comment by Samuelsheehan** [comment]
**扩展选项页**
![QQ截图20220118123327](https://user-images.githubusercontent.com/68676065/149871818-5f26e376-f3bb-4cc0-9d05-033cc8ce5963.png)
**背景页**
![image](https://user-images.githubusercontent.com/68676065/149872163-858053ba-e26d-4665-93fe-4b8a09c41ec9.png)
![image](https://user-images.githubusercontent.com/68676065/149872203-652793ec-2e21-4797-8a41-b8f0435b6b29.png)

**Comment by zimocode** [comment]
这情况有点奇怪了。
请重启浏览器后，把背景页中的所有报错（红色）截图下。

**Comment by Samuelsheehan** [comment]
![image](https://user-images.githubusercontent.com/68676065/149913466-5ffd03b4-f5a1-4650-9684-30b8c04c7165.png)
![image](https://user-images.githubusercontent.com/68676065/149913711-0e788f3e-5370-4dbb-b89e-88ba5d80a043.png)
