### ISSUE TITLE
关闭标签页的确认选项无效

### ISSUE THREAD

**Issue by naskater** [zimocode/smartup#190]
更新到最新版后，鼠标手势中的“关闭其他标签页”和“关闭所有标签页”失效了

**Comment by onionycs** [comment]
#  不好意思借个楼反馈个bug
 
## 鼠标手势 `关闭其他标签页` 没有失效， `但是` 在关闭大于1个标签页时，手势的提醒好像没用。。。

![bug](https://user-images.githubusercontent.com/37523020/149846031-fd9e4143-fb24-4c5d-9d94-a4623d2e7328.png)

 ## 如上图所示，点击取消后还是会关闭所有的其余标签页。

**Comment by naskater** [comment]
不好意思，是我自己在flags设置里面开启了某项实验性功能导致的失效，并非smartup问题，特来说明。
