### ISSUE TITLE
拖拽是否能禁止在picviewer产生的大图上生效？

### ISSUE THREAD

**Issue by YandLiu** [zimocode/smartup#195]
我用了[picviewer这个脚本](https://greasyfork.org/zh-CN/scripts/24204-picviewer-ce)，发现超级拖拽也会在大图上生效，不过在Imagus生成的大图上无效https://github.com/zimocode/smartup/issues/89

由于PicViewer产生的大图经常需要拖动，因此需求与用Imagus时正好相反
![15DBF927](https://user-images.githubusercontent.com/26127104/152684184-bea9ea20-0e2a-49c3-9a8d-8d8ff73ac7a1.png)

**Comment by zimocode** [comment]
能不能给个测试页面😂

**Comment by zimocode** [comment]
我这里测试在大图上不能拖曳的呀

**Comment by YandLiu** [comment]
刚发现原来不是所有网站都有问题

Smartup配置：
https://gist.github.com/YandLiu/a5d97a6f0e8a5c4b50855b5244d6b308

下面这张动图是在B站首页截的

![动画2](https://user-images.githubusercontent.com/26127104/152797104-1ef71683-beb0-49ad-a945-16c1eb796a51.gif)

**Comment by zimocode** [comment]
我这测试的b站，就你动图那位置，脚本生成的图片，能正常拖动呀，smartup在这图片上没有工作。
会不会是其它脚本或者扩展影响了😂

**Comment by YandLiu** [comment]
明了了，这奇葩问题是由这个扩展导致的
https://microsoftedge.microsoft.com/addons/detail/%E6%9C%80%E7%BB%88%E5%90%AF%E7%94%A8%E5%8F%B3%E9%94%AE%E5%8D%95%E5%87%BB/ijopbbfjlehabpldjiaipgiiedhfhbad

抱歉给你带来了不必要的麻烦😔
