### ISSUE TITLE
能否加个“关闭右侧标签页”和“关闭其它标签页”？

### ISSUE THREAD

**Issue by oopsea** [zimocode/smartup#196]
如题。

**Comment by zimocode** [comment]
![image](https://user-images.githubusercontent.com/29518677/152740298-c5a6f52b-5e89-4437-9f83-b00f7f3c511b.png)

**Comment by oopsea** [comment]
> ![image](https://user-images.githubusercontent.com/29518677/152740298-c5a6f52b-5e89-4437-9f83-b00f7f3c511b.png)

谢谢。
