### ISSUE TITLE
能否添加在某些网站上禁用的设置

### ISSUE THREAD

**Issue by zbt000** [zimocode/smartup#197]
今天发现在一个网站(minesweeper.online)上会冲突

**Comment by zimocode** [comment]
有啥冲突呢，我这里简单试了下，没发现问题。
PS：有个计划是加上黑白名单功能。

**Comment by dougpuob** [comment]
我也需要這個功能。我在使用 Google Chrome Remote Desktop (https://remotedesktop.google.com)，有時後在遠端機器上看網頁，卻常誤動作把連線中的網頁關了。如果有這個功能就太好了，很期侍。

**Comment by Unintendedz** [comment]
很需要这个功能，经常需要在 https://lucid.app/ 画图，在它这里右键是用来拖动视图的。

**Comment by reniaL** [comment]
同求这个功能。
例如，在幕布 (https://mubu.com/home )上，浏览思维导图时，按住鼠标右键拖动，是移动画布的功能。比较方便。
希望能在一些特定站点上禁用这个扩展～

**Comment by dougpuob** [comment]
Hi @zimocode , I tried it, and it works now. Thank you ^.^
