### ISSUE TITLE
[Firefox]Right Context Menu will auto click the first item and disappear

### ISSUE THREAD

**Issue by c02y** [zimocode/smartup#198]
- Firefox 96.0.3
- Arch Linux + i3 + picom
- smartup 7.0.131.1131

When there are two programs side by side, the first item in the right Context Menu will be auto clicked and the menu will disappear.

1. it happens not only in web page, it happens too when you select multiple tabs and try to close them
2. it happens when you right click on a link or on the plain text in the page
3. I've tested it with Firefox Private mode + default SmartUp config
4. I'm using i3 on Arch Linux, this happens when in tiling mode, when you float the Firefox window, this issue is gone, when you make it tiling again, it is OK too.

I'm not sure if you can reproduce it in other environment, if you need anything else, please let me know.

![Peek 2022-02-08 12-31](https://user-images.githubusercontent.com/2135996/152918601-e4a20bcd-e57a-4979-b018-e4ed9e9d2529.gif)

**Comment by oneironaut2209** [comment]
https://wiki.archlinux.org/title/Bspwm#Firefox_context_menu_automatically_selects_first_option_on_right_click

**Comment by c02y** [comment]
> https://wiki.archlinux.org/title/Bspwm#Firefox_context_menu_automatically_selects_first_option_on_right_click

Thanks for the llink. It works fine when I use Firefox without SmartUp extension. It is more likely a bug of SmartUp

**Comment by oneironaut2209** [comment]
> > https://wiki.archlinux.org/title/Bspwm#Firefox_context_menu_automatically_selects_first_option_on_right_click
> 
> Thanks for the link. It works fine when I use Firefox without SmartUp extension. It is more likely a bug of SmartUp
> 
> And I've tried the solution in the link, it doesn't work.

https://wiki.archlinux.org/title/Firefox#Right_mouse_button_instantly_clicks_the_first_option_in_window_managers

This one worked for me. Try it

**Comment by c02y** [comment]
> > > https://wiki.archlinux.org/title/Bspwm#Firefox_context_menu_automatically_selects_first_option_on_right_click
> > 
> > 
> > Thanks for the link. It works fine when I use Firefox without SmartUp extension. It is more likely a bug of SmartUp
> > And I've tried the solution in the link, it doesn't work.
> 
> https://wiki.archlinux.org/title/Firefox#Right_mouse_button_instantly_clicks_the_first_option_in_window_managers
> 
> This one worked for me. Try it

Thanks, it does work
