### ISSUE TITLE
Increment URL

### ISSUE THREAD

**Issue by yaisuah** [zimocode/smartup#2]
Extension works great except when Incrementing or Decrementing the URL, if it ends with a 0 then # like 01.html, it always removes the 0 to become just 1.html.   Anyway to fix this?  Thanks.

**Comment by zimocode** [comment]
Can you give me a URL for testing?

**Comment by yaisuah** [comment]
https://commons.wikimedia.org/wiki/File:Vlad_Tepes_001.jpg  Random one I just found.
