### ISSUE TITLE
feature suggestion / 3 screenshot modes

### ISSUE THREAD

**Issue by tockschmock** [zimocode/smartup#206]
it would be very nice, if the 3 screenshot modes Chrome OS offers:
1. selected frame
2. clicked window
3. full screen

could be linked to different gestures.

Even better, gestures options with or without the follow-up Chrome OS notification options:
- Edit (opens the screenshot for immediate editing)
- Show in Folder

**Comment by zimocode** [comment]
chrome os is different with chrome browser, so ...

**Comment by tockschmock** [comment]
oh yes, I confused things
