### ISSUE TITLE
没有火狐版了?

### ISSUE THREAD

**Issue by chwt163** [zimocode/smartup#209]
如题

**Comment by zimocode** [comment]
![image](https://user-images.githubusercontent.com/29518677/156696017-fa27dd37-97a5-431b-9d85-af652c8131ff.png)
![image](https://user-images.githubusercontent.com/29518677/156696035-b2000832-3d9e-49fe-966f-91b4b1606694.png)
被下架了，最近一直没时间处理，争取下周。
