### ISSUE TITLE
When closing a tab the "parent" tab will be closed, too!

### ISSUE THREAD

**Issue by Tronic69** [zimocode/smartup#21]
Hello, 

since last update (to version 6.1.1108.837 from Oct 1st) sometimes I have a curious problem in Vivaldi browser (currently using 2.1.1322.4). When I open a new tab from a link in a tab like Webmail or ToDo list and then close the "child" tab the "parent" tab will be closed, too! 

It does not happen every time, but very often and it's really annoying! 

Any ideas what causes this behavior and how to avoid it? 

Thanks in advance,
Tom

**Comment by zimocode** [comment]
Sorry, no plans to fit vivaldi
