### ISSUE TITLE
any text after the symbol & is excluded from search

### ISSUE THREAD

**Issue by Hossam225** [zimocode/smartup#212]
Using text drag to search any site for a text that contains the symbol **&** always ignore the symbol with the text after. Let's say dragging the text "**Young & Beautiful (2013)**" to be searched with google search engine.. it shows results for the inquiry "**young**" only.

**Comment by tockschmock** [comment]
correct observation
tested on Chrome OS Version 99.0.4844.57

**Comment by zimocode** [comment]
encode type choose another one:
![image](https://user-images.githubusercontent.com/29518677/158009693-86ed9060-ff33-48a0-a961-6844bce9fd01.png)

**Comment by Hossam225** [comment]
> encode type choose another one: ![image](https://user-images.githubusercontent.com/29518677/158009693-86ed9060-ff33-48a0-a961-6844bce9fd01.png)

Thanks that works.
