### ISSUE TITLE
火狐文字拖曳功能失效

### ISSUE THREAD

**Issue by BaiBuCYBGT** [zimocode/smartup#218]
更新后很多网页无法文本拖曳，有些网页要复制一次链接再进入才生效，有些网页无论如何都不生效
不生效的网页 例 https://www.mozilla.org/en-US/firefox/98.0.1/releasenotes/
刷新或者复制链接重新进入的网页 例 百度
火狐 98.0.1x64
smartUp手势 Ver 7.1.376.1147 全默认设置

**Comment by zimocode** [comment]
昨天已经提交了一个更新，请升级到最新的1148版本
