### ISSUE TITLE
拖拽图片 没有转到图片链接功能

### ISSUE THREAD

**Issue by iamking2211** [zimocode/smartup#219]
拖拽图片 没有转到图片链接功能
请求增加  拖拽图片后直接跳转链接的功能
设置里面的 (视为图片，如果该链接包含有图片)  选不选都一样 没区别

**Comment by zimocode** [comment]
这个有点难度

**Comment by yjd** [comment]
Cent Browser用惯了刚好也要问这个。
判定图片链接带 <a href=就优先跳转这个链接，是否可行？
