### ISSUE TITLE
Feature request: Mouse Gestures - Actions - Close right/left tabs

### ISSUE THREAD

**Issue by remio87** [zimocode/smartup#225]
Thank you so much for developing such a superb extension. I love it!
Here is a only feature I would like to have in addition - close all the right or left tabs as an action of the mouse gestures.
This function is common in the other gesture extensions, and I'm a heavy user of that.
It would be appreciated if the developers could consider its possibility.

**Comment by tockschmock** [comment]
This would be easy if we could trigger the features of other extensions with gestures

For example ths extension 
[https://github.com/crittermike/shortkeys](url)
provides the commands, that can be triggered via keyboard shortcuts.

As far as I understood zimocode however, this is technically impossible to implement:
 [https://github.com/zimocode/smartup/issues/146#issue-875194946](url)
[https://github.com/zimocode/smartup/issues/213#issue-1161743297](url)

**Comment by zimocode** [comment]
![image](https://user-images.githubusercontent.com/29518677/161666548-aeaf11eb-0663-470c-b7d8-9f83d4c206f6.png)

**Comment by remio87** [comment]
Oh, I just missed that feature... Thanks!!
