### ISSUE TITLE
SU gestures (unfortunately) not working in reader mode (Chrome OS)

### ISSUE THREAD

**Issue by tockschmock** [zimocode/smartup#236]
text drags do not work in the reader view mode of Chrome
a fix would be great

![Screenshot 2022-04-17 19 44 00](https://user-images.githubusercontent.com/68165681/163726245-10a0e737-6845-47bc-bb29-d5a7d316793f.png)

**Comment by zimocode** [comment]
Operation is prohibited in this mode, so it cannot be implemented
