### ISSUE TITLE
Copy Image or Whatever like Ctrl+C

### ISSUE THREAD

**Issue by waingt** [zimocode/smartup#241]
I did't find an option to perform an Ctrl+C like copy. Text copy only copy texts. Link copy only copy links. Images copy only copy image link. There's no way to copy an combination of them.
Please give an option to copy selected image or whatever anything which is selected (links, texts, images)
like this `document.execCommand("copy");` according to https://stackoverflow.com/questions/69310964/javascript-copy-text-and-image-to-clipboard

**Comment by zimocode** [comment]
copy images fixed #171

**Comment by waingt** [comment]
> copy images fixed #171

369ca7f seems to be a screenshot style copy.
I would like, for example, to super drag the selected and paste it into Microsoft Word to keep its format unchanged.
Ctrl+C certainly can do this

**Comment by zimocode** [comment]
> > copy images fixed #171
> 
> [369ca7f](https://github.com/zimocode/smartup/commit/369ca7fae99effec416f396d3fca50b6cc931837) seems to be a screenshot style copy. I would like, for example, to super drag the selected and paste it into Microsoft Word to keep its format unchanged. Ctrl+C certainly can do this

Browsers do not allow such operations
