### ISSUE TITLE
【建议】自定义组合快捷键来实现功能

### ISSUE THREAD

**Issue by naskater** [zimocode/smartup#246]
![2](https://user-images.githubusercontent.com/22311485/179337795-f4619276-492f-44d6-8938-500a16d9dbff.jpg)
![1](https://user-images.githubusercontent.com/22311485/179337798-4dc58a51-ebd0-4f04-b07d-7a5919df2604.jpg)

如图，浏览器都自带一些快捷键功能。所以想到一个建议：可否考虑在smartup中添加一个自定义组合快捷键功能，让用户可以在鼠标手势、摇杆手势、滚轮手势中触发浏览器自带的对应快捷键，从而实现相应功能。例如浏览器自带的关闭标签页键盘快捷键是ctrl+w，用户可以在鼠标手势中设置一个手势，手势的命令用户就可以设置成ctrl+w的快捷键，从而实现关闭标签页的功能。这样一来，smartup可以无需增加更多的功能选项却能使用户获取更多的功能需求。现在pc端有一些本地全局手势软件已经具备这个功能，希望作者能考虑一下，借鉴进来，感谢！

**Comment by zimocode** [comment]
不能实现，因为浏览器本身限制了扩展不能调用这些快捷键。
