### ISSUE TITLE
Проблема!

### ISSUE THREAD

**Issue by Spok1** [zimocode/smartup#249]
Жесты колесом + кнопка мыши при уменьшении масштаба сбрасывает масштаб до 100 вместо 10.
Сделайте жест, чтобы можно было с помощью жестов скопировать юрл текущей вкладки;

**Comment by zimocode** [comment]
![image](https://user-images.githubusercontent.com/29518677/187057003-21553794-df55-4236-b267-2d370c58b3a6.png)
![image](https://user-images.githubusercontent.com/29518677/187057031-666fb733-e4e6-4d09-befd-1d6f0f8a1ea3.png)

**Comment by Spok1** [comment]
Thank you! But the problem with the step when zooming out using wheel gestures is not solved: the step is used, as in the image, so that the scale decreases with the standard step in the browser, otherwise it will immediately reset to 100%, for example, from 150%. Also make it possible to open a new tab in incognito mode instead of duplicating with the current address.

![image](https://user-images.githubusercontent.com/34476664/187098240-21b78cd3-93c3-4660-a50c-232f39a95e7f.png)
