### ISSUE TITLE
smartUp Gestures

### ISSUE THREAD

**Issue by Oohbaby** [zimocode/smartup#25]
Hi
Some web pages's links cannot be opened in a background/foreground tab with Mouse Gestures.
Simple Drag opens all links, though.
Can you fix this?

Best Regards
Georges Walther

**Comment by zimocode** [comment]
Can you give these links? or other extensions interference？

**Comment by Oohbaby** [comment]
Hi

Here are two sites where 'Open Link' with gesture is not working:

https://www.chip.de/
https://www.srf.ch/news/international

Best regards
Georges Walther

**Comment by zimocode** [comment]
Hi,
It works for me . Have you installed other similar extensions？

**Comment by Oohbaby** [comment]
Hi

*CLEAN crxMouse Gestures*  and *Smooth Gestures Plus* are installed but not
on.

Regards
Georges Walther

**Comment by zimocode** [comment]
1) add another user in chrome
2) install smartup 
3) try again

**Comment by Oohbaby** [comment]
Thanks for the clue but this didn't solve the problem.
Regards

**Comment by zimocode** [comment]
Please send me you config file, zimocode#@#gmail.com

**Comment by Oohbaby** [comment]
What config file?

**Comment by zimocode** [comment]
general>configuration>Export Configuration

**Comment by Oohbaby** [comment]
Ah, yes. Here it is.

**Comment by Oohbaby** [comment]
Hi

Have you found a solution to the 'Open Link'- issue yet?

Regards
Georges
