### ISSUE TITLE
启动浏览器需要刷新一次页面手势才能用

### ISSUE THREAD

**Issue by smdx** [zimocode/smartup#250]
浏览器是Cent Browser 5.0.1002.182测试版（旧版本也有这个问题）、smartUp 7.1.382.1148，启动浏览器后当前页面需要刷新一次手势才能用。试过同样是用Chromium内核的猫眼浏览器没这个问题，请问在cb浏览器要怎么设置解决？谢谢

**Comment by zimocode** [comment]
这个是浏览器本身的限制，无解。
