### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '%'

### ISSUE THREAD

**Issue by mikeparkie** [zimocode/smartup#253]
Hi there, 

Firstly, great extention! 

I'm trying you use the **Save as web page** [bookmarklet](https://www.inoreader.com/apps ), I've loaded the script into the config and when I run the bookmarklet it produces the below error: 

`javascript:function p(a,w,h){var b=window.screenLeft!=undefined?window.screenLeft:screen.left;var c=window.screenTop!=undefined?window.screenTop:screen.top;width=window.innerWidth?window.innerWidth:document.documentElement.clientWidth?document.documentElement.clientWidth:screen.width;height=window.innerHeight?window.innerHeight:document.documentElement.clientHeight?document.documentElement.clientHeight:screen.height;var d=((width/2)-(w/2))+b;var e=((height/2)-(h/2))+c;var f=window.open(a,new Date().getTime(),%27width=%27+w+%27, height=%27+h+%27, top=%27+e+%27, left=%27+d+%27location=yes,resizable=yes,status=no,scrollbars=no,personalbar=no,toolbar=no,menubar=no%27);if(window.focus){f.focus()}}p(%27https://www.inoreader.com/bookmarklet/save_web_page/%27+encodeURIComponent(location.href),640,400)`

Error: Uncaught SyntaxError: Unexpected token '%'

I have used other bookmarklets without issue, and using the boomarklet on the bookmarks bar works correctly, just fails when calling it through using the extention.  

Smartup Verrsion:  7.1.382.1148
Edge Version: 104.0.1293.70 (Official build) (64-bit)

**Comment by zimocode** [comment]
``` javascript
javascript:function p(a,w,h){var b=window.screenLeft!=undefined?window.screenLeft:screen.left;var c=window.screenTop!=undefined?window.screenTop:screen.top;width=window.innerWidth?window.innerWidth:document.documentElement.clientWidth?document.documentElement.clientWidth:screen.width;height=window.innerHeight?window.innerHeight:document.documentElement.clientHeight?document.documentElement.clientHeight:screen.height;var d=((width/2)-(w/2))+b;var e=((height/2)-(h/2))+c;var f=window.open(a,new Date().getTime(),'width='+w+', height='+h+', top='+e+', left='+d+'location=yes,resizable=yes,status=no,scrollbars=no,personalbar=no,toolbar=no,menubar=no');if(window.focus){f.focus()}}p('https://www.inoreader.com/bookmarklet/save_web_page/'+encodeURIComponent(location.href),640,400)
```

**Comment by mikeparkie** [comment]
Perfect, thanks so much for the speedy response!
