### ISSUE TITLE
incognito mode!

### ISSUE THREAD

**Issue by Spok1** [zimocode/smartup#254]
Make it possible to open a new tab in incognito mode instead of duplicating the current url in it.

**Comment by zimocode** [comment]
![image](https://user-images.githubusercontent.com/29518677/187944352-63bdb46e-5c06-4d47-a040-74ebbeb9d180.png)

**Comment by Spok1** [comment]
Yes, I saw it, but, as I already wrote, this parameter opens the current tab with its contents in incognito mode, which is not what I want! I want a clean tab!

**Comment by zimocode** [comment]
![image](https://user-images.githubusercontent.com/29518677/187950872-1b818ee9-0a79-4350-93c0-17d274856a94.png)

**Comment by zimocode** [comment]
e....
seems to have a bug

**Comment by zimocode** [comment]
OR:
![image](https://user-images.githubusercontent.com/29518677/187961213-4510f6c8-f792-4c24-9836-66d842b8bffa.png)
