### ISSUE TITLE
Edge浏览器105.0.1343.27不能触发鼠标手势

### ISSUE THREAD

**Issue by talentldk** [zimocode/smartup#258]
如题，win10系统，Edge浏览器105.0.1343.27不能触发鼠标手势，拖拽功能正常，滚轮手势也正常。
使用chrome浏览器可以触发鼠标手势。

**Comment by zimocode** [comment]
能说说具体情况么？首次安装就不能正常使用，还是说以前正常，今天突然出问题了？最近是否安装了其它的扩展？

**Comment by talentldk** [comment]
刚才又突然能用了，我也没有重启重装之类的，就很神奇。
