### ISSUE TITLE
7.1.1212.1154在firefox下新建标签页不工作

### ISSUE THREAD

**Issue by GithubUsername3** [zimocode/smartup#261]
windows7 64位，firefox 104 64位，更新smartup到7.1.1212.1154后，使用新建标签页手势，没有产生新的标签页，google chrome没有这个问题

**Comment by zimocode** [comment]
方便导出你的配置文件发我一下吗？

**Comment by lucifersun** [comment]
smartup Ver 7.1.1212.1154
Firefox Ver 104.0.2 (64 bit)
发现同样问题，新建标签页不生效。
附上配置文件
[smartup.zip](https://github.com/zimocode/smartup/files/9523560/smartup.zip)

**Comment by zimocode** [comment]
有个地方Firefox的处理方式不一样，已经做了回滚。
