### ISSUE TITLE
"New Tab" gesture not working since last extension (or last Firefox) update 

### ISSUE THREAD

**Issue by rombat** [zimocode/smartup#262]
Hi
I'm running this extension in version 7.1.1212.1154 with Firefox 104.0.2 on Windows 11.
The extension has been updated yesterday, and Firefox 2 days ago, so I don't really now who the culprit is.
The thing is, it was working perfectly fine before, but now, "New Tab" gesture (up) is not working anymore. The others seems to work fine, at least the one I've tried.
Is there any way to fix this ?
Thanks in advance and have a nice day

**Comment by zimocode** [comment]
a new version (7.1.1212.1155) has been uploaded to AMO,  it should fixed it.
