### ISSUE TITLE
Actions with a down movement stopped working on Chrome 105

### ISSUE THREAD

**Issue by Tete1805** [zimocode/smartup#264]
Hello,

I don't know if anyone else has experienced this, but since the last Chrome update (105), when I right-click and go down, the action is discarded and the right click menu opens up.
It happens consistently any time I go down, all other movements are ok.
I'm on Ver 7.1.1212.1154 and Chrome 105.0.5195.102.

For information, it works with the middle button.

**Comment by zimocode** [comment]
can you upload your config?

**Comment by Tete1805** [comment]
So I switched back to crxMouse when it happened.
I just switched back to smartup and now I can't reproduce the issue. (It works ok, no Chrome update, same smartup version.)
Sorry, I have no idea why it happened.
