### ISSUE TITLE
No output Configuration button on setting page / 设置页看不到导出按钮

### ISSUE THREAD

**Issue by AmazonXYZ** [zimocode/smartup#273]
![image](https://user-images.githubusercontent.com/36888603/196691167-39777043-00b9-41f4-b937-7e8e77725531.png)
Ver 7.1.1225.1160
106.0.1370.47 (正式版本) (64 位) 
Windows 11 Version 22H2 (Build 22621.674)
Edge 商店版本

仅在我第一次截图时刷出来一次，还以为我之前看错了

**Comment by 132conan** [comment]
我刚才也遇到了这个问题，就跑到issues来看看有没有提问，然后跑回去刷新了一下，又出现了导出按钮

尝试复现了一下，大概是这样的：
打开选项，点击通用选项，点击配置管理，看不见导出按钮，然后点击权限管理，再点配置管理，又看见了导出按钮

**Comment by Flashwalker** [comment]
Actualy, you can still export. The export button is commented out. I don't know why the developer did this. It's so silly.
Just open the developer tools and comment out the button: see video:
[uncomment-the-button.webm](https://user-images.githubusercontent.com/2188215/203699732-8ca8f62e-ff04-4b4a-b284-5661cfa4ef6c.webm)
