### ISSUE TITLE
复制图片选项丢失

### ISSUE THREAD

**Issue by zcw1030** [zimocode/smartup#290]
您好，两台电脑，smartup、chrome版本相同，但其中一台没有复制图片选项，玄学了。

**Comment by lethefrost** [comment]
请问你的问题解决了吗？我的电脑上也没有复制图片，只有复制图片链接

**Comment by zcw1030** [comment]
> 请问你的问题解决了吗？我的电脑上也没有复制图片，只有复制图片链接

您好，仍然没有解决。一台电脑有复知图片选项，另一台没有。

**Comment by lethefrost** [comment]
> > 请问你的问题解决了吗？我的电脑上也没有复制图片，只有复制图片链接
> 
> 您好，仍然没有解决。一台电脑有复制图片选项，另一台没有。

请问你的电脑是什么平台的呢？我在一台朋友的windows上试了下有复制图片，我的是macOS，没有这个选项，我们chrome和smartup版本一样，会不会和系统有关？
