### ISSUE TITLE
Is there a reason why Chrome version is not up to date?

### ISSUE THREAD

**Issue by Jenie7** [zimocode/smartup#296]
Edge and Firefox seem to have the newer version, unlike Chrome.

**Comment by zimocode** [comment]
Didn‘t pass the Chrome Web Store's review
![image](https://user-images.githubusercontent.com/29518677/204073366-8b890f53-94d0-4408-9921-e76d91f464e1.png)

**Comment by Jenie7** [comment]
Sorry about that.

I'll just switch to the Edge version after I make a backup, which would make more sense for me, because I'm using Edge.

**Comment by zimocode** [comment]
the new version is on the way , should passed the review in few days.
