### ISSUE TITLE
关闭多个标签的问题

### ISSUE THREAD

**Issue by GithubUsername3** [zimocode/smartup#3]
chrome和firefox都有以下同样问题，firefox建立新profile也是如此：

1.使用关闭全部右边标签手势，如果当前标签在最右端，即其右边没有任何标签时，会把左边全部标签关闭；反之亦然，使用关闭全部左边标签手势，如果当前标签在最左端，即其左边没有任何标签时，会把右边全部标签关闭。

我认为正确的操作应该是：关闭全部右边标签手势只关闭右边标签，不论当前标签右边是否还有标签；关闭全部左边标签手势只关闭左边标签，不论当前标签左边是否还有标签

2.为防误操作，提供的关闭多个标签(全部左边、全部右边、其它)时的确认功能有bug，在弹出确认提示时，无论是否点击确认还是取消，都会照样执行关闭操作。

我认为正确的操作应该是：关闭多个标签手势在弹出确认提示时，点击取消，就不执行手势

**Comment by zimocode** [comment]
1) 这个是考虑不周，跟其它的操作共用的一套逻辑，没注意到；

2) 这个我再确认下，本来的计划也是准备再改进下这部分。
