### ISSUE TITLE
如何关闭edge里smartup的通知权限

### ISSUE THREAD

**Issue by yexiaoziSAS** [zimocode/smartup#302]
smartup在edge里的notifications权限无法取消关闭。请问怎么操作来关闭？
<img width="789" alt="屏幕截图 2022-12-14 144135" src="https://user-images.githubusercontent.com/79674263/207524709-59199428-4b0c-4e2e-969b-4bacde340610.png">

**Comment by yexiaoziSAS** [comment]
<img width="1007" alt="屏幕截图 2022-12-15 153030" src="https://user-images.githubusercontent.com/79674263/207799402-57862cda-b8fc-48a8-9d94-d9fdea11bc92.png">

**Comment by zimocode** [comment]
这个权限是用来提示一些信息的，没有设置为可选权限，但是使用的很少，为啥想着要禁止这个权限呢？

**Comment by yexiaoziSAS** [comment]
感谢作者回复。主要是想只看到手势图标缺不需要文字提示，可否将通知设置成能自行开关的模式

**Comment by zimocode** [comment]
目前很少会出现提示呀。你是使用了啥手势，每次都要提示么？如果是这样的话，相应的手势设置里面有不通知的选项的。
主要是关闭这个权限，涉及到改动的地方较多。

**Comment by yexiaoziSAS** [comment]
<img width="575" alt="屏幕截图 2023-04-05 102628" src="https://user-images.githubusercontent.com/79674263/229965302-fba9b641-7f08-41bb-b4e3-12a6376d9dc3.png">
你好，应该是我没描述清楚。我指的是红色圈出部分的提示，能否自定义开关

**Comment by zimocode** [comment]
这玩意儿默认没有打开的呀。
这个是页面内的操作提示

**Comment by zimocode** [comment]
![image](https://user-images.githubusercontent.com/29518677/229968592-b5317be2-0521-4a0b-a623-f9d1aaecf13b.png)

**Comment by yexiaoziSAS** [comment]
收到，原来是设置问题。感谢了
