### ISSUE TITLE
Last/First tab mouse gesture actions

### ISSUE THREAD

**Issue by Mecawento** [zimocode/smartup#303]
Hello could it be possible to add to Mouse Gestures Actions an option to move to the last tab (rightmost) and another opposite option to move to the first tab (leftmost)?

Also another question please, Im confused with the extension settings and I would like to ask if there is a way to open a link that is contained inside a picture in a webpage. I have tried several settings but I cannot open links embedded in images I only manage to open the image in another tab.

I think this last question is related to this issue:
https://github.com/zimocode/smartup/issues/286

I use Chrome browser. Thank you very much for your help

**Comment by tockschmock** [comment]
This command is already implemented:
Switch Tab: Head or Last

**Comment by Mecawento** [comment]
> This command is already implemented: Switch Tab: Head or Last

Hello thank you for the feedback you are right your comment solves the problem I just didnt know there were sub-actions for most of the Smartup Gestures actions list.

However I leave this issue opened for the extension developer to close it because he seems missing in action and also I would like to suggest a better and more detailed documentatin for this amazing github project with for example a better explanation of all actions and subactions list

Also last but not least issue #286 is still incredibly annoying and important to fix because it makes this extension nearly useless since half the links in the internet are embedded in images nowadays

Thanks
