### ISSUE TITLE
Scroll Up and Down command not precise 

### ISSUE THREAD

**Issue by tockschmock** [zimocode/smartup#311]
Unfortunately one of the most important gestures/commends, namely Scroll Up and Scroll Down are not precise.
Compared to the keyboard scrolls (Space / Shift+Space and PgUp/PgDN) the SUG commands scroll too much lines, so that text at the intersections between scrolls remains hidden.
Very sad for this otherwise amazing extension.
Please fix the scroll command so that it behaves exactly like the keyboard initiated equivalents without hiding text in between.

**Comment by zimocode** [comment]
scroll too much lines？
