### ISSUE TITLE
隐身模式中打开关闭的标签页失效

### ISSUE THREAD

**Issue by anonymou3** [zimocode/smartup#314]
能否追加功能隐身模式中正常的打开关闭的标签页  
发现该插件能做到 [tab-reopen-key-on-incogni](https://chrome.google.com/webstore/detail/tab-reopen-key-on-incogni/alkfhfgkepamooonkjdolamnbilhkmjg)

**Comment by zimocode** [comment]
按常理来说，隐身模式不应该实现该功能。
但是真正的原因是，Firefox禁止了该操作，为了保持chrome与firfox两个平台的一致性，就都跳过了隐身模式。
