### ISSUE TITLE
刚更新的 7.2.486.1164 在火狐下不工作了

### ISSUE THREAD

**Issue by elfmm** [zimocode/smartup#324]
刚自动更新了 7.2.486.1164，然后就发现鼠标手势完全不工作了，重启浏览器，重启电脑都还是不行，只能退回 7.1.1355.1162

火狐版本：111.0.1
win10

**Comment by zimocode** [comment]
不至于吧，这次这是修复了一些bug，没有大的改动呀。

**Comment by RiffraDD** [comment]
win11也用不了，同一个版本

**Comment by zimocode** [comment]
@RiffraDD @elfmm 能给点更多信息不。
