### ISSUE TITLE
Exclusion (blacklist) stopped working

### ISSUE THREAD

**Issue by Weissrolf** [zimocode/smartup#338]
Hello.

SmartUp Gestures is one of the few gesture addons that allows to use a blacklist for excluding sites. This worked in the past, but now unfortunately seems broken (tested in Egde and Chrome). Gestures now keep working on excluded sites instead of being disabled as before.

**Comment by trump888** [comment]
+1

**Comment by MauTenSquare** [comment]
+1 (was looking for an alternative to crxMouse exactly 'cause I wanted exclusions to work)

**Comment by MauTenSquare** [comment]
isn't it just that changing this in event.js would fix it? 
Your function gets a pattern `*.google.com/*` and produces a `/^.*.google.com\/*$/` RegExp object. That doesn't then match the url which is, say 'www.google.com/search'. 
But if you were just to remove the *s and add a couple `/`s it appears like it could work?

![image](https://user-images.githubusercontent.com/129502710/236536038-1e903578-ff4b-4e79-bb4e-5ab7271ee039.png)

I've done a little test, and it appears to work fine, for me, if I change your event.js line 341 from:

		`const regexes = patterns.map(pattern => new RegExp('^' + pattern.replace('*', '.*') + '$'));`

to 

		`const regexes = patterns.map(pattern => new RegExp(  pattern.replaceAll('*', '')));`

please let me know if that does something bad I can't quite grasp, I've not looked too deeply into it. If you want a PR no problem, though I suppose for one single line it might not quite be worth it.

**Comment by vorrin** [comment]
+1 (was looking for an alternative to crxMouse exactly 'cause I wanted exclusions to work)


isn't it just that changing this in event.js would fix it?
Your function gets a pattern *.google.com/* and produces a /^.*.google.com\/*$/ RegExp object. That doesn't then match the url which is, say 'www.google.com/search'.
But if you were just to remove the *s and add a couple /s it appears like it could work?

![236536038-1e903578-ff4b-4e79-bb4e-5ab7271ee039](https://user-images.githubusercontent.com/1560703/236537943-b665923e-43eb-49b7-a450-a14bf53b87aa.png)


I've done a little test, and it appears to work fine, for me, if I change your event.js line 341 from:

	`const regexes = patterns.map(pattern => new RegExp('^' + pattern.replace('*', '.*') + '$'));`
to

	`const regexes = patterns.map(pattern => new RegExp(  pattern.replaceAll('*', '')));`

please let me know if that does something bad I can't quite grasp, I've not looked too deeply into it. If you want a PR no problem, though I suppose for one single line it might not quite be worth it. Thanks for the nice extension :)

**Comment by vorrin** [comment]
well, or I guess, even better (I tried to understand the whys of your type of regex), probably just change `replace` to `replaceAll`, that also works :D

**Comment by vorrin** [comment]
surprisingly, that still doesn't work for me: 
![image](https://user-images.githubusercontent.com/1560703/236638794-6575554b-e6e3-4d22-bba6-a05df22b1c9d.png)
and:
![image](https://user-images.githubusercontent.com/1560703/236638802-93725ab9-dabd-420e-afdc-0cb8c1439211.png)

**Comment by Weissrolf** [comment]
Thanks for the fix, but it has only been pushed to the Firefox store so far. Both Chrome and Edge store still host the older version 1168.

**Comment by zimocode** [comment]
the new version has been uploaded to the store, just wating for review.

**Comment by vorrin** [comment]
Ah I see, of course, I stupidly thought that step would be pretty much immediate, but if course it is not cause there's stores involved. I should have tested pulling latest from here instead. Thanks for clarifying!
