### ISSUE TITLE
导入配置提示升级到最新版本

### ISSUE THREAD

**Issue by xuan880** [zimocode/smartup#35]
重新安装浏览器的时候导入之前备份的配置文件，提示需要升级到最新版本，明明软件已经是mozilla上的最新版本了，github上面也没有最新的安装文件，根本没法用呀。

**Comment by lovestudygithub** [comment]
Mozilla上面的最新版本是5.1不是最新的，最新的已经6.xxx了，所以才会出这个提示，找一台已经升级到6.xxx版本的机子，找到下面的文件C:\Users\xxx\AppData\Roaming\Mozilla\Firefox\Profiles\xxxxxx.default\extensions\{77b19bb0-313b-49c8-9e58-cef2e4ebf317}.xpi，拷到你要安装的机子上，从文件安装就ok了。每台机的xpi文件名不一定一样，最简单的判断办法就是，用解压文件打开xpi文件看一下里面的change.log文件是否跟官网的更新log一样就知道是不是smartup的xpi文件了。

**Comment by xuan880** [comment]
> Mozilla上面的最新版本是5.1不是最新的，最新的已经6.xxx了，所以才会出这个提示，找一台已经升级到6.xxx版本的机子，找到下面的文件C:\Users\xxx\AppData\Roaming\Mozilla\Firefox\Profiles\xxxxxx.default\extensions\ {77b19bb0-313b-49c8-9e58-cef2e4ebf317}.xpi，拷到你要安装的机子上，从文件安装就ok了。每台机的xpi文件名不一定一样，最简单的判断办法就是，用解压文件打开xpi文件看一下里面的change.log文件是否跟官网的更新log一样，就知道是不是smartup的xpi文件了。

问题就是Mozilla上没有最新版本，GitHub上6.xx的版本找不到，手让没有6.xx的xpi文件的话根本没法升级。希望在GitHub上面提供一下，或者把Mozilla上的版本升级一下。

**Comment by lovestudygithub** [comment]
> 
> 
> > Mozilla上面的最新版本是5.1不是最新的，最新的已经6.xxx了，所以才会出这个提示，找一台已经升级到6.xxx版本的机子，找到下面的文件C:\Users\xxx\AppData\Roaming\Mozilla\Firefox\Profiles\xxxxxx.default\extensions\ {77b19bb0-313b-49c8-9e58-cef2e4ebf317}.xpi，拷到你要安装的机子上，从文件安装就ok了。每台机的xpi文件名不一定一样，最简单的判断办法就是，用解压文件打开xpi文件看一下里面的change.log文件是否跟官网的更新log一样，就知道是不是smartup的xpi文件了。
> 
> 问题就是Mozilla上没有最新版本，GitHub上6.xx的版本找不到，手让没有6.xx的xpi文件的话根本没法升级。希望在GitHub上面提供一下，或者把Mozilla上的版本升级一下。

我分享一下现在为止最新v6.1.1108.837的XPI文件，链接: https://pan.baidu.com/s/1jkPRGYa09xCPsL2qCrWTPg 提取码: dgz6

**Comment by zimocode** [comment]
你好，Mozilla将最新版下架了，保留的是一个很老的版本才导致的这问题。目前已经重新提交新版，等待审核中。

**Comment by YandLiu** [comment]
现在AMO上的smartUp版本和Chrome Web Store里的一样，都是6.5.1348.1026，但是从Firefox导出的配置导入Chrome时也会提示需要升级
