### ISSUE TITLE
[feature request] increment/decrement number in url

### ISSUE THREAD

**Issue by rawdez** [zimocode/smartup#37]
trying to use it with this
https://data.whicdn.com/images/238008360/original.jpg
results in this
https://data.whicdn.com/images/238008360/original.jpgNaN

**Comment by zimocode** [comment]
This action is only valid for URLs that are numeric at the end

**Comment by rawdez** [comment]
but why not make it to increment any last numeral in a url, like search for a numeral from the end and increase/decrease it. would be a very convenient feature.
probably should change this issue to a feature request than.
