### ISSUE TITLE
Gestures do not open links in tabs for Google websites

### ISSUE THREAD

**Issue by jtulp** [zimocode/smartup#38]
I have set shortcuts for open link in tab (left, right) and open link in tab on the background (right, left).

This works on nearly all sites, but not for my search-results on google.com and google.nl

**Comment by zimocode** [comment]
Other extension interference？

**Comment by jtulp** [comment]
I checked in incoginto mode with only smartUp as allowed extension and it still occures.
The tooltip for the smartUp icon shows it has access to the page,

It (not opening upon gesture) also occures on the news items on the Dutch news site nu.nl

**Comment by zimocode** [comment]
It works for me.
Other extensions have permissions to run in incognito mode？

**Comment by jtulp** [comment]
No, I made sure only smartUp was enabled.
I also tested with a clean session (my work uses Citrix, where Chrome is always started clean) and it also does not work. I maded sure only 1 gesture was available (could only remove the last 1 after the LR-gesture):

See enclosed screenshots

**Comment by zimocode** [comment]
Only one gesture?
image 1,LR
but image 2,RL
please send me the config file, zimocode#@#gmail.com

**Comment by jtulp** [comment]
Correct, my mistake. Enclosed the proper example.

![smartup3](https://user-images.githubusercontent.com/7070075/52864180-e49e7e80-3139-11e9-8e09-a119ccb0aaf0.jpg)

**Comment by jtulp** [comment]
Issue is not resolved dor me.
I tried updating smartUp (switching to developer mode), but version remains 6.1.1108.837.

**Comment by Userfrettchen** [comment]
i have the same issue
is this still a problem with google search / results?
