### ISSUE TITLE
Settings ignored for 'Previous Page' and 'Next Page' actions

### ISSUE THREAD

**Issue by a-ch-chu** [zimocode/smartup#4]
Settings:
- Customization action name: No
- Gesture: RL and LR, respectively
- Note for this action: none
- Show the note in the tab.: No
- Key words: defaults
- Open Type: Current
- Position: Any
- Pin the tab: No

Behaviour: The gestures sometimes open the previous or next page in a new, foreground, non-incognito tab at the last position.

Expected Behaviour: That the previous or next page be always opened in the current tab.

Platform: Google Chrome 67.0.3396.87 (Official Build) 64-bit, Windows 10 x86_64

**Comment by zimocode** [comment]
Hi,
It works. Can you send me your config file, zimocode#gmail.com

**Comment by zimocode** [comment]
Hi, you may try to change the options ,like this:
![image](https://user-images.githubusercontent.com/29518677/44296164-53199580-a2eb-11e8-9761-180ba06e13f4.png)
