### ISSUE TITLE
Open Link works only with simple links

### ISSUE THREAD

**Issue by 80lin08** [zimocode/smartup#43]
Open Link detects links by looking "href" of only current element, but on many websites (youtube, for example) links consists of many elements, like \<a href=..\>\<img ...>\<span>link name\</span>\</a>

So, my solution is to just lookup parent elements too (add something like "seekHref").
https://gist.github.com/80lin08/ac7c308937a2486d8154dd8579e877e6

**Comment by deathtrip** [comment]
I also noticed that smartup opens only certain links, while failing on others.
Very annoying, as it makes the "Open Link" gesture unreliable.
Hopefully this will be fixed.
