### ISSUE TITLE
Firefox中的扩展版本非常陈旧

### ISSUE THREAD

**Issue by McGiRG3z** [zimocode/smartup#46]
开发者你好，

目前Firefox中最新版仅仅为Version 5.1.1240.747(Sep 27, 2017)，我翻看您之前[这个问题](https://github.com/zimocode/smartup/issues/35)中2月14日回复已经等待审核，可是目前已经3月25日，仍然没能更新。

**Comment by zimocode** [comment]
Mozilla的扩展后台有bug，提交不上，提交了issue，一直没进展😥

**Comment by McGiRG3z** [comment]
> 
> 
> Mozilla的扩展后台有bug，提交不上，提交了issue，一直没进展disappointed_relieved

😂现在好像下架了...

**Comment by zimocode** [comment]
> > Mozilla的扩展后台有bug，提交不上，提交了issue，一直没进展disappointed_relieved
> 
> 😂现在好像下架了...

提交更新的时候，一下说这里不规范，一下又是那里不符合要求。把历史版本删的差不多了，最新的版本变成了近两年前的了。跟Mozilla沟通的时候已经表明了：要完全符合他们的要求，我的工作量很大，本来这就是个业余的项目，我哪那么多精力更新呢？叫他暂时给通过，后面我再慢慢更新符合其要求，结果一直大太极。刚才下班回来一气之下干脆直接下架了，惹不起。眼不见心不烦😂
等啥时候代码改的符合Mozilla要求了再重新上架吧。

**Comment by McGiRG3z** [comment]
> 
> 
> > > Mozilla的扩展后台有bug，提交不上，提交了issue，一直没进展disappointed_relieved
> > 
> > 
> > joy现在好像下架了...
> 
> 提交更新的时候，一下说这里不规范，一下又是那里不符合要求。把历史版本删的差不多了，最新的版本变成了近两年前的了。跟Mozilla沟通的时候已经表明了：要完全符合他们的要求，我的工作量很大，本来这就是个业余的项目，我哪那么多精力更新呢？叫他暂时给通过，后面我再慢慢更新符合其要求，结果一直大太极。刚才下班回来一气之下干脆直接下架了，惹不起。眼不见心不烦joy
> 等啥时候代码改的符合Mozilla要求了再重新上架吧。

哦哦, 原来是这样呀...
有听说过AMO审核极为苛刻...能够理解您❤!!!
为Firefox暂时失去这样好用的扩展感到惋惜....🙃
谢谢您这么用心更新和答复!!!辛苦了!!!👍
