### ISSUE TITLE
need to double click on a link

### ISSUE THREAD

**Issue by dymn** [zimocode/smartup#49]
Sometimes need to double click on a link to open it. This behavior is only with this gestures extension.
There is a suspicion that the first click falls on some hidden advertising on top of the link layer.
Also installed Ublock origin, Umatrix.
Linux x86_64, Google Chrome 74.0.3729.108.

**Comment by zimocode** [comment]
Maybe, destroyed by other extensions?

**Comment by dymn** [comment]
I dont know. Scripts and ads are blocked only by Ublock and Umatrix. Maybe something invisible remains.
But such behavior only with this extension of gestures. Moreover, there is an advertisement in this extension, although it is disabled in the settings.

There is another suspicion that this behavior happens after the computer resume from suspend, if Chrome was launched.

**Comment by zimocode** [comment]
Did you try to disabled smartup?

**Comment by dymn** [comment]
I disabled the smartup and installed other extensions of gestures. Everything worked without problems.

**Comment by dymn** [comment]
And yes, I found out that this it is not related to resume from suspend.

**Comment by zimocode** [comment]
I dont have a linux device for now, I'll try to install an linux system to check it.

**Comment by dcts** [comment]
I am having the exact same issue! I am on Linux and have only SmartUp gestures extension installed. If i uninsstall it, everything works fine again. 

Did you find any solutions to this so far? @zimocode @dymn ?

**Comment by dymn** [comment]
No, I switched to Firefox
