### ISSUE TITLE
Rocker gestures does not work reliably in Firefox

### ISSUE THREAD

**Issue by andrewz1986** [zimocode/smartup#5]
Hi. I use latest SmartUp extension in latest Firefox version. I set rocker gestures to move back and forward in history of currently displayed page, but ometimes it does not work at all, sometimes more clicks are required and sometimes context menu appears inadvertently. When going through history by other gestures, it works fine.

![obrazek](https://user-images.githubusercontent.com/40487872/41766748-19861574-7608-11e8-8174-cd0f6255977f.png)

**Comment by zimocode** [comment]
history of currently displayed page?

**Comment by andrewz1986** [comment]
Have a look at the screenshot. It shows exactly what action I'm talking about. What I meant was simply moving back and forward, which is also possible through left and right arrows next to reload button. But it actually does not matter. The registration of rocker gestures alone is broken, because it does not work properly no matter what action I assign to it.

**Comment by zimocode** [comment]
Got it.

**Comment by terrorist96** [comment]
I have the same problem but in Chrome. I have rocker gesture set to go back and forth (but opposite as your config). 
Left-click with holding right button mouse gesture is programmed to go back, and it does go back successfully, **but it doesn't suppress the context menu** even though I have "do NOT pop up context menu" enabled in the general settings.

**Comment by terrorist96** [comment]
@zimocode why was this closed? I still have this issue on `6.8.1233.1117`.
