### ISSUE TITLE
Often show as damaged when added by local .crx files

### ISSUE THREAD

**Issue by AltheaL55** [zimocode/smartup#50]
Often show as damaged when added by local .crx files. Each time this issue could be solved temporarily by dragging .crx files into chrome again, but soon it will occur again.

**Comment by zimocode** [comment]
Chrome does not support installing .crx files by local, please install it from the chrome web store.
[https://chrome.google.com/webstore/detail/bgjfekefhjemchdeigphccilhncnjldn](https://chrome.google.com/webstore/detail/bgjfekefhjemchdeigphccilhncnjldn)
