### ISSUE TITLE
 create gestures with hot keys 

### ISSUE THREAD

**Issue by urururuuu** [zimocode/smartup#55]
expansion gestures for googlechrome  smart Up Please tell me how to create gestures with hot keys, for example, the combination of keys alt + ctrl + shift + 1.2.3.4 e.t.c

**Comment by zimocode** [comment]
like this ?:
https://chrome.google.com/webstore/detail/smartkey-shortcuts/aogbgmnbacmlobiajlmjhmbecjohglnl

**Comment by s94039403** [comment]
I think he maybe means like thie: if I use "right" gesture then input "alt+x"
