### ISSUE TITLE
What are "Icon Action" and "Popup Action"?

### ISSUE THREAD

**Issue by ayuanx** [zimocode/smartup#6]
There should be a Wiki to explain these things. But I can't find it, neither in the extension itself or in its home website, which is this repo.

**Comment by ayuanx** [comment]
All right. After fumbling around and click everything, I finally figured out myself.

"Icon Action" is the action when you click on SmartUp icon.
"Popup Action" pops up a menu when you click on SmartUp icon.

Should have added these simple texts in the extension already!

Still not sure the function of "Context Menu". Is it the context menu in the page, or the context menu on SmartUp icon? I deselected it but I can still see "New tab" in both of them!

**Comment by zimocode** [comment]
Yes, it is.
"context menu", is in the page, but, on the icon by chrome, too.
