### ISSUE TITLE
Smartup does not work on first tab when Chrome is started

### ISSUE THREAD

**Issue by valynor** [zimocode/smartup#62]
Installed latest Smartup version from Chrome webstore. 
Chrome Version 76.0.3809.100 (Official Build) (64-bit) on Linux Mint 19.2.

When I launch Chrome with tabs open from the previous session, Smartup does not work at all on the first tab that opens - it does work on all other tabs after switching to them. 
To make it work on the first tab I have to reload that tab. This happens every time I start Chrome.

**Comment by zimocode** [comment]
Because of chrome limitations, the code is not yet running when chrome is just open.

**Comment by valynor** [comment]
Well .. I am using miniGestures [Reloaded]* for several years now and not **once** did it not work on the 1st tab when I launched Chrome. Maybe there is something you can do to fix your extension. 


* https://chrome.google.com/webstore/detail/minigestures-reloaded/beamjpgknhidkfgmbeplfedbnhmajjpj
