### ISSUE TITLE
如何在鼠标手势修改操作界面增加新的列表项

### ISSUE THREAD

**Issue by qkhyjp** [zimocode/smartup#63]
![image](https://user-images.githubusercontent.com/46615206/63585413-a0e96d80-c5d1-11e9-8fe8-e5dc70fadb5e.png)
完全没找到任何地方进行这个操作，提示的点X删除倒是看见了，点+增加一直没找到，感觉很不人性化。

**Comment by zimocode** [comment]
你好，在你这截图的右下角应该有个加号按钮：
![image](https://user-images.githubusercontent.com/29518677/63598776-d3f02900-c5f2-11e9-9800-f06c5e87ca78.png)
不过，看你这截图似乎没有这个按钮....
请你提供更多信息，比如扩展版本，浏览器信息等，或者将配置文件导出发我看看。

**Comment by zimocode** [comment]
看你的界面，应该是高分屏，那个加号按钮估计位置有点偏下。你这倒是提醒了我，下次更新的时候看看能不能做点改动。
