### ISSUE TITLE
Cant use dict.cc or google translate as a search engine for simple-dragging text

### ISSUE THREAD

**Issue by ars4l4n** [zimocode/smartup#67]
Hi,

I wanted to simple-drag selected portions of text to hit them into a translator immediately. Using the 2 websites above as the search engine didn't work. 
(I did use the default links like translate.google.com and also tried using variations of the link by clicking on the specific languages to translate again so I got https://translate.google.com/#view=home&op=translate&sl=auto&tl=en for example for Autodetect->English and that didn't work either)
Do you perhaps know a way to do it?`
Maybe you add it as a default feature? Because that's quite the useful productivity tool for a substantial amount of everyday users. I saw you added some note on how to format URLs but I didn't understand what to do with that.
____
EDIT:
I figured out how to do it by trying around stuff. 
https://translate.google.com/?hl=de&tab=TT&authuser=0#view=home&op=translate&sl=auto&tl=en&text=tea
and instead of "tea" you put in "%s" 
but you might add some default options there and/or put in a roughly detailed example on how to swap out keywords with "%s" so that users can add languages themselves.

You should add dict.cc as a default translator (https://www.dict.cc/?s=%s) because it gives you results in 2 languages immediately (based on your cookies I think).
Add google translator as an option for people who want to translate entire phrases

Best Regards,

ars4l4n

**Comment by zimocode** [comment]
https://translate.google.com/?hl=de&tab=TT&authuser=0#view=home&op=translate&sl=auto&tl=en&text=%s
