### ISSUE TITLE
Bug: 与 Chrome 自带的托至标签栏的处理动作（可能）同时触发

### ISSUE THREAD

**Issue by xuchkang171** [zimocode/smartup#70]
![20191117 smartup bug](https://user-images.githubusercontent.com/5658598/69001793-c90e1180-091f-11ea-9ae6-d0e17dc54bf7.gif)
图示：托至标签栏，预期结果是在特定位置新建搜索（Chrome 自带功能），但同时误触发了 smartup 的右划搜索动作。

当托拽至标签栏时，如果托离 window（Javascript Window Object）前、在起点 window 内最后被捕捉的鼠标终点处于 smartup 有效动作的判定区域内，则会误触发 smartup 动作。此时，更大概率应该是，用户只是想使用 Chrome 自带的托拽动作：比如在开了众多 tab 的情况下，为在某个确定地点新建搜索或打开链接，而托拽文本/链接至当前浏览器窗口标签栏的空白处、某个标签上、某两个标签之间或者（可能在副显示器的）另一窗口。

所以，当托拽的终点是标签栏时（或者说，更大的，当前 window 之外时），应该取消 smartup 动作的执行吧，如可触发。

**Comment by zimocode** [comment]
印象中，很久之前有个类似于你描述的这种情况，为了避免冲突，做了判定的。
而且，就我的测试来看，不会发生你说的这种情况。能否告知你的浏览器版本，或者新建个用户，只安装本扩展测试下。
