### ISSUE TITLE
缺少“关闭非当前标签”或“关闭其它标签”标签动作

### ISSUE THREAD

**Issue by Iongtimenosee** [zimocode/smartup#71]
“关闭非当前标签”或“关闭其它标签”，这个动作大多数鼠标手势功能都支持的，建议加上。我用的是火狐浏览器版本。

**Comment by zimocode** [comment]
添加新操作后，选择关闭标签页，在目标标签页中选择“其它”即可。
![image](https://user-images.githubusercontent.com/29518677/70385465-927c6180-19c8-11ea-97b5-1f2256859c21.png)

**Comment by Iongtimenosee** [comment]
不好意思没注意细节，我直觉还以为只能关闭一个。感谢回复，祝身体健康。
