### ISSUE TITLE
Save Image As... is not using the last save folder in Firefox

### ISSUE THREAD

**Issue by rawdez** [zimocode/smartup#73]
every time using Save Image As... on image you have to choose a folder.
it always opens a default one instead of the last one. 

firefox 71.0 (64-bit)
win 10 64-bit
smartup version 6.5.1348.1026

**Comment by lpslp** [comment]
+1
because of that i simply CAN NOT use smartUp Gestures!

**Comment by lpslp** [comment]
probably what we mentioned here the developer can solve when Firefox 78 will show up according this
https://github.com/Robbendebiene/Gesturefy/issues/145#issuecomment-629712943
