### ISSUE TITLE
【bug】chrome下，超级拖拽里，文本操作有问题。

### ISSUE THREAD

**Issue by Beating-flies** [zimocode/smartup#74]
开发者：
您好！

我使用smartup扩展，在文本操作里设置第15个搜索文本时，遇到bug。表现为拖拽不能使用，我自定义的配置消失。此问题出现在chrome浏览器下，firefox没有此问题。

**Comment by zimocode** [comment]
能具体描述下“在文本操作里设置第15个搜索文本时”吗？

**Comment by Beating-flies** [comment]
我把我的配置文件分享给你，请尝试下。删掉文件名末尾的 .txt 。

超级拖曳》文本操作》右下角加号添加》编辑操作选搜索文本》随便一个文本引擎。
[smartup.config.txt](https://github.com/zimocode/smartup/files/4204917/smartup.config.txt)

**Comment by Beating-flies** [comment]
刚发现，firefox 文本转语音有问题，不能使用。迷你应用文本朗读也有问题，不能使用。

**Comment by zimocode** [comment]
> 刚发现，firefox 文本转语音有问题，不能使用。迷你应用文本朗读也有问题，不能使用。

这个文本转语音，调用的是浏览器的api来实现的，而Firefox目前还没有实现该api，所以目前不能使用。

**Comment by zimocode** [comment]
> 我把我的配置文件分享给你，请尝试下。删掉文件名末尾的 .txt 。
> 
> 超级拖曳》文本操作》右下角加号添加》编辑操作选搜索文本》随便选一个文本引擎。
> [smartup.config.txt](https://github.com/zimocode/smartup/files/4204917/smartup.config.txt)

已确认问题存在，感谢反馈。

**Comment by zimocode** [comment]
你好，已经确认是配置文件太大，超过配额引起的😂
可以通过在配置管理里面，取消勾选`自动同步配置`来正常使用，但是扩展的配置不会同步，只能通过自行导出来保存。
后门争取对这种情况做判断，超额后回滚到上一次的配置，避免重置为默认配置。
