### ISSUE TITLE
可以加入双击关闭标签的功能吗？

### ISSUE THREAD

**Issue by zingplus** [zimocode/smartup#77]
希望可以加入双击关闭标签的功能，双击标签即可快速关闭。

**Comment by zimocode** [comment]
暂时没法实现

**Comment by zingplus** [comment]
插件Double Click Closes Tab，双击页面空白处关闭标签，虽然不是双击标签栏，但感觉可以借鉴一下

**Comment by zimocode** [comment]
> 插件Double Click Closes Tab，双击页面空白处关闭标签，虽然不是双击标签栏，但感觉可以借鉴一下

双击页面的空白处可以实现，但是我觉得意义不大，且容易误操作。

**Comment by zingplus** [comment]
谢谢
