### ISSUE TITLE
鼠标重置缩放

### ISSUE THREAD

**Issue by Ukiyo-E** [zimocode/smartup#78]
希望添加以下功能，先按下鼠标右键，后按下鼠标左键，重置缩放为 100%

**Comment by zimocode** [comment]
![image](https://user-images.githubusercontent.com/29518677/74015000-beb55e00-49ca-11ea-95b4-a1d894ae09c0.png)
![image](https://user-images.githubusercontent.com/29518677/74015097-eefcfc80-49ca-11ea-829e-09aad7bda7ba.png)

**Comment by Amitahui** [comment]
感谢回复哈，原来鼠标摇杆手势是这个意思，这下完美了。我还有一个小问题哈，在编辑操作里面有两个缩放，见下图高亮条目
![SmartUp](https://user-images.githubusercontent.com/25998789/74061023-282c7100-49b9-11ea-98b1-188b189680eb.png)
一个是在其他分类下面，一个是在即将删除分类下面。当设置为其他分类下面的缩放时，在我这里（chrome 版本 80.0.3987.87）没有任何效果，但是设置为即将删除分类下面的缩放时，是有效果的。
这个不知道是有意为之还是 bug，即将删除是后续版本要移除的意思吗？谢谢解答哈

**Comment by zimocode** [comment]
其它分类里面的缩放是通过chrome的api来实现的，浏览器能保存缩放记录；
即将删除分类里面的缩放是api出来之前，通过js来实现的，不能保存缩放记录，整体上来看缩放的效果没有浏览器直接实现的理想，后期也不再维护。

**Comment by Amitahui** [comment]
是浏览器新版本的原因吗，我的目前依然没有任何效果

**Comment by zimocode** [comment]
> 是浏览器新版本的原因吗，我的目前依然没有任何效果

应该不至于吧。方便的话，把你的配置发出来我看看。

**Comment by Amitahui** [comment]
见附件，Win 10 1909 64位，同时安装有&nbsp;uBlock Origin1.24.4 插件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zimocode"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月8日(星期六) 中午12:24
收件人:&nbsp;"zimocode/smartup"<smartup@noreply.github.com&gt;;
抄送:&nbsp;"Amitahui"<408226724@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zimocode/smartup] 添加鼠标重置缩放功能 (#78)



 
是浏览器新版本的原因吗，我的目前依然没有任何效果
  
应该不至于吧。方便的话，把你的配置发出来我看看。

**Comment by zimocode** [comment]
> 见附件，Win 10 1909 64位，同时安装有&nbsp;uBlock Origin1.24.4 插件
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"zimocode"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月8日(星期六) 中午12:24 收件人:&nbsp;"zimocode/smartup"<smartup@noreply.github.com&gt;; 抄送:&nbsp;"Amitahui"<408226724@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [zimocode/smartup] 添加鼠标重置缩放功能 (#78) 是浏览器新版本的原因吗，我的目前依然没有任何效果 应该不至于吧。方便的话，把你的配置发出来我看看。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没看见你的附件哟，到git上提交，不要用邮件。

**Comment by zimocode** [comment]
换80版本试了下，真有问题😂。
80版本应该是beta版，初步怀疑是浏览器版本引起的。下午再仔细看看。

**Comment by Amitahui** [comment]
> 换80版本试了下，真有问题😂。
> 80版本应该是beta版，初步怀疑是浏览器版本引起的。下午再仔细看看。

OK，辛苦了，thx
