### ISSUE TITLE
Small settings window

### ISSUE THREAD

**Issue by TuTAH1** [zimocode/smartup#8]
in Chrome and Firefox it's about 300px height. It's too small! ![1](https://user-images.githubusercontent.com/15982179/42724246-51e4ce38-8788-11e8-8837-0d8c72ccc9b3.jpg)
 Please make it higher or maybe even fit to page space

**Comment by zimocode** [comment]
The browser did this.
You may click the icon ,select options to open options page,or, draw RDLU to open by default.
