### ISSUE TITLE
Gesture for unmuting?

### ISSUE THREAD

**Issue by random-un** [zimocode/smartup#83]
smartUp Gestures support a "Mute tab" action -- how about an "Unmute tab" action? Would be great to have that option as well!

![image](https://user-images.githubusercontent.com/35006176/74493214-46e1aa80-4e86-11ea-910f-a07805e9905a.png)

**Comment by zimocode** [comment]
YES.
Do the action first, it's mute, and ,do the action again, it's unmute.
