### ISSUE TITLE
扩展申请剪贴板权限时申请反了

### ISSUE THREAD

**Issue by YandLiu** [zimocode/smartup#85]
`clipboardWrite`和`clipboardRead`申请反了，复制链接时申请写，粘贴文本时申请读
另外自带的粘贴文本会在网页里新建一个文本框却不去掉

**Comment by zimocode** [comment]
文本框在哪个页面出现？chrome还是firefox？

**Comment by YandLiu** [comment]
不管是什么页面都会出现
Firefox

**Comment by zimocode** [comment]
还真是把权限申请反了😓

**Comment by zimocode** [comment]
> 不管是什么页面都会出现
> Firefox

看了下确实申请反了，因为我这里读写的权限都有，所以测试的时候没发现。
