### ISSUE TITLE
【bug 与建议】超级拖曳下，修改画线操作有问题。

### ISSUE THREAD

**Issue by Beating-flies** [zimocode/smartup#87]
开发者：
您好！

我在编辑修改「超级拖曳」里的功能时，发现 bug。在文本操作、连接操作和图片操作里，在修改选项下编辑画线里，实际操作与提示语的说明不符。我需鼠标右键画线才能修改。提示语里的内容，我无法操作。
此问题出现在 chrome 和 firefox 下。包括 smartup 6.6、6.5 版。

顺便提个建议：修改操作下的选项，同时显示操作名称和备注。
现在，它只显示操作名称，我设置了太多选项，查找其中一个比较困难。

**Comment by Beating-flies** [comment]
还有，您的个人网站，部分崩了。下面的链接，自功能介绍以下，都打不开。
https://smartup.zimoapps.com/zh_CN/docs/index.html

**Comment by zimocode** [comment]
BUG存在很久了，一直没想起来处理，争取修复；
同时显示备注可以考虑下；
网站内容还没来得及完善。
