### ISSUE TITLE
Too many console.log

### ISSUE THREAD

**Issue by wildwind3325** [zimocode/smartup#88]
what the hell is event.js? it records every keydown and prints the keycodes, every navigation prints status(?).

**Comment by Zhwt** [comment]
估计问题出在没有调用这个函数重置一下 console.log 函数, 本应该在开发模式下输出的现在全都输出了

https://github.com/zimocode/smartup/blob/53bd41aaf935a0fc1d5bf69f3ef52ce6f2922fcc/js/event.js#L41-L47
