### ISSUE TITLE
线条和提示的位置出现偏移

### ISSUE THREAD

**Issue by zhoujia456888** [zimocode/smartup#9]
在浏览默写网页的时候，我在鼠标的位置右键画手势，线条的位置和提示的位置会出现偏移，并不是跟随鼠标指针的位置。
![qq20180810-154043](https://user-images.githubusercontent.com/7905253/43945173-f357a7f0-9cb3-11e8-9ff1-7cb696443815.png)
如图。（截图的时候鼠标指针隐藏了）。
我大概试了一下，基本上是在评论区会有这种情况，在正文区不会有这种情况。（测试的网址是IT之家和驱动之家）。
Chrome 版本 68.0.3440.106（正式版本） （64 位）
Mac OS 版本10.13.6

**Comment by cyqw** [comment]
使用iframe的页面都有问题
