### ISSUE TITLE
希望上架Microsoft Store~

### ISSUE THREAD

**Issue by lc190cc** [zimocode/smartup#90]
edge在chrome store里安装好像不能后续更新，希望上架微软的商店！

**Comment by zimocode** [comment]
微软还没开放扩展提交，只要能上架，我就会去上架的（别太贵就成😂）

**Comment by zhanghao1989** [comment]
> 微软还没开放扩展提交，只要能上架，我就会去上架的（别太贵就成😂）

新版edge不是已经开放了吗? "新版 Edge 插件商店面向开发者开放，支持现有插件迁移"

**Comment by zimocode** [comment]
> > 微软还没开放扩展提交，只要能上架，我就会去上架的（别太贵就成😂）
> 
> 新版edge不是已经开放了吗? "新版 Edge 插件商店面向开发者开放，支持现有插件迁移"

有链接么？

**Comment by zhanghao1989** [comment]
> > > 微软还没开放扩展提交，只要能上架，我就会去上架的（别太贵就成😂）
> > 
> > 
> > 新版edge不是已经开放了吗? "新版 Edge 插件商店面向开发者开放，支持现有插件迁移"
> 
> 有链接么？

新闻链接https://blog.csdn.net/mzl87/article/details/103638709
微软开发者文档19年12月6号的https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension?branch=extensions-documentation

**Comment by zimocode** [comment]
@lc190cc @Sheep-12 
已经提交：https://microsoftedge.microsoft.com/addons/detail/elponhbfjjjihgeijofonnflefhcbckp
目前提交的版本是chrome里面的最新版，未做测试，后续再慢慢完善。

**Comment by Sheep-12** [comment]
好的,应该没问题,之前都是edge用着chrome商店的版本

**Comment by lc190cc** [comment]
谢啦！
