### ISSUE TITLE
[REQUEST] Close other Tabs Gesture

### ISSUE THREAD

**Issue by miguedevel** [zimocode/smartup#92]
As title says, I'd like a gesture action added for closing other tabs than current tabs or background tabs in other words. Also one for closing tabs to the right of the active one.

Thanks.

**Comment by zimocode** [comment]
Hi,it include these actions.
![image](https://user-images.githubusercontent.com/29518677/76855671-9273e380-688c-11ea-949c-13789a7e4426.png)

**Comment by miguedevel** [comment]
Thanks, hadn't noticed that.
