### ISSUE TITLE
chrome浏览器隐私模式不能调用普通模式下的设置

### ISSUE THREAD

**Issue by GithubUsername3** [zimocode/smartup#93]
chrome和opera浏览器都是这样，每次进入隐私模式，smartup总是使用该扩展初始默认的手势，而不是使用在普通模式下修改好的手势。

firefox没有这个问题。

**Comment by zimocode** [comment]
第一次听说这种情况。我这测试没你说的这种情况，能给些详细信息么？比如：chrome版本号等。

**Comment by GithubUsername3** [comment]
没事了，我搞清怎么回事了。

2018年我做过smartup扩展设置的备份，最近恢复设置时用了该备份，估计年代相差较远造成的。

现在重新设置好后，再次导入、导出，再也没有发生问题了

**Comment by YandLiu** [comment]
Edge上也有这个问题
Edge：版本 91.0.864.64 (官方内部版本) (64 位)
Smartup：最新版本

**Comment by YandLiu** [comment]
Edge上也有这个问题
Edge：版本 91.0.864.67 (官方内部版本) (64 位)
SmartUp是从Chrome Web Store装的最新版
