### ISSUE TITLE
能否将 event.js 中的调试信息去掉

### ISSUE THREAD

**Issue by songlingxi** [zimocode/smartup#94]
![123123123](https://user-images.githubusercontent.com/5064328/77025620-8bec8580-69cc-11ea-8847-36236b24f863.png)

**Comment by wangxian** [comment]
强烈支持，很影响 前端用控制台调试~

**Comment by zimocode** [comment]
ff？

**Comment by wangxian** [comment]
是的

**Comment by zimocode** [comment]
> 是的

之前误操作，把开发版提交到了AMO。已经更正了。
